services:
   dns:
    build: 
      context: ./conf-dns
      dockerfile: Dockerfile
    container_name: DNS
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
       isp_network:
          ipv4_address: 172.25.0.2