networks:
  client01_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
    attachable: true

incluide:
  - path: ./Proxy/docker-compose-proxy.yaml
  - path: ./Portal/docker-compose-portal.yaml
  - path: ./Hotsite/docker-compose-hostsite.yaml
  - path: ./Sign/docker-compose-sign.yaml